### ISSUE TITLE
rb-appscript causing segmentation fault?

### ISSUE THREAD

**Issue by jstortz** [devondragon/jira-omnifocus#1]
I forked it.  Downloaded it.  Edited configs.  Installed gems.  Ran it.  Erred out.  I am getting what looks like a segmentation fault based on rb-appscript.  Here are my versions of everything if you care to compare against yours:

ruby-2.0.0-p353
rb-appscript (0.6.1)
json-1.8.1

What version of ruby and rb-appscript are you running?

**Comment by devondragon** [comment]
I'm going to close this out.  If this is still an issue, please let me know!
