### ISSUE TITLE
Task sync

### ISSUE THREAD

**Issue by koolkhel** [devondragon/jira-omnifocus#10]
Hello.

I'm not sure about use case for this script.

Why does it create task duplicates after running repeatedly? I guess, it shoudn't import tasks with already existing issue keys, but it does, so I wonder, if it is right.

Thanks for the great job!

**Comment by koolkhel** [comment]
Actually, I see

# Check to see if there's already an OF Task with that name in the referenced Project
  # If there is, just stop.
  name   = new_task_properties["name"]
  exists = proj.tasks.get.find { |t| t.name.get == name }
  return false if exists

but it doesn't seem to work in my case (Cyrillic, perhaps)

**Comment by koolkhel** [comment]
name   = new_task_properties["name"]
  exists = proj.tasks.get.find { |t| t.name.get.force_encoding("UTF-8") == name }
  return false if exists

seems to work ok

**Comment by devondragon** [comment]
Thanks!  I will make the fix in the code here shortly!

**Comment by koolkhel** [comment]
Thanks :-)
