### ISSUE TITLE
Provide an option to use HTTP instead of HTTPS

### ISSUE THREAD

**Issue by koolkhel** [devondragon/jira-omnifocus#11]
My company's JIRA is available through HTTP only.

Thus, I need to manually edit JIRA_BASE_URL variable, and I think this is bad.

**Comment by devondragon** [comment]
I've updated the code, and the example config file, to put the scheme (http vs https) in the configured hostname property instead of assuming HTTPS in the code.  It should be workable for you at this point.

**Comment by koolkhel** [comment]
Thanks!
I guess, you also need to fix in-code documentation:
=begin
YAML CONFIG EXAMPLE
---
jira:
  hostname: 'example.atlassian.net'
  username: 'jdoe'
  password: 'blahblahblah'
  context: 'Jira'
  project: 'Work'
  flag: true
  filter: 'assignee = currentUser() AND status not in (Closed, Resolved) AND sprint in openSprints()'
=end

Anyways, thanks a lot for a useful (for me) script :-) I wonder if it would be hard to complete jira tasks from omnifocus.

**Comment by devondragon** [comment]
Good point!  Updated and committed.
