### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by robrecord** [devondragon/jira-omnifocus#12]
/Users/robrecord/Applications/jira-omnifocus/bin/jiraomnifocus.rb:4:in `<main>': private method `require' called for Bundler:Module (NoMethodError)

No idea what this means!

**Comment by devondragon** [comment]
You installed Bundler and ran bundle install from within the lira-omnifocus directory?

**Comment by devondragon** [comment]
Closing due to lack of follow-up and many changes made since March.
