### ISSUE TITLE
Feature: add comments into notes in omnifocus

### ISSUE THREAD

**Issue by poshpaws** [devondragon/jira-omnifocus#25]
issue / tasks with comments , i would love to see in the notes section

**Comment by devondragon** [comment]
I have updated it so that the ticket description is in the notes.  However I'm not sure I want to add in comments.  Some of the tickets I deal with have 100+ comments, and having them all in a OF note would be very unwieldy.

**Comment by poshpaws** [comment]
Shame , at least the last comment would have been handy , I am basically jiraphobic and try to stay out of jira as long as possible

**Comment by devondragon** [comment]
Well, let me see if there's a reasonable way for me to make it an option.  I need to figure out how to format  large number of comments in a way that they are easily readable....
