### ISSUE TITLE
Nothing happened when run the .rb script

### ISSUE THREAD

**Issue by yqrashawn** [devondragon/jira-omnifocus#29]
I followed the readme, added the configuration file. But when I run the script. Nothing happened. It just keep running and never stopped until Ctrl-C.

**Comment by devondragon** [comment]
Is OmniFocus running at the time?  Can you add some debugging but putting some puts statements in and see where it's getting stuck?  Sorry I don't have an easy debugging flag (although I should add that).

**Comment by devondragon** [comment]
I have updated the script with a ton of debug statements.  You can run it manually from the checked out directory like this:  ruby -d bin/jiraomnifocus.rb

There will be a lot of Exceptions, which appear to be "normal" but that should still provide some rudimentary flow tracing and allow us to see what is happening in your scenario.

@yqrashawn could you please update, and run the script manually as above and email me the output (so you don't have to paste any private URLs or task IDs, etc...)

**Comment by yqrashawn** [comment]
Been busy these days.

Thanks. yqrashawn.
On Thu, Oct 6, 2016 at 5:00 AM, Devon Hillard <notifications@github.com> wrote:
Assigned #29 [https://github.com/devondragon/jira-omnifocus/issues/29] to @yqrashawn [https://github.com/yqrashawn] .
