### ISSUE TITLE
Any interest in deferring issues not in current sprint?

### ISSUE THREAD

**Issue by protomartyr** [devondragon/jira-omnifocus#31]
Hey All,

Since my team works in sprints, I'm always manually deferring my Jira issues within OmniFocus that aren't in the current sprint. I'm working on adding a method in the script that grabs all your Jira issues that are not in an open sprint, and then defers the related OF tasks to the following Sunday (that way they'll be available again next Monday, and if a new sprint starts and the issue is not in that sprint, the script will defer it again). 

Is there any interest if I refine it a little more (and maybe add some logic so that this method only runs once or twice a day) and add it to a PR?

**Comment by lgrassini** [comment]
Hi @protomartyr sounds interesting. 
In my company we don't know what is going to happen in the next sprint. Is just in the sprint planning that we will know for sure what we'll be working on.

I think is a very nice to have feature. I would suggest to keep a flag in .jofsync.yaml for activating/deactivating this.

Regards!

**Comment by devondragon** [comment]
Would be happy to see a PR for this, but agree that it would need to be driven off of a flag in the config file, so it wouldn't impact the rest of us:)  Thanks!!  Let me know if you need help at all, although we don't do Sprint based work so I don't have good data points to test with...

**Comment by devondragon** [comment]
I am going to close this out due to lack of activity.  If anyone wants to work on it and submit a PR we can re-open or a create a new issue.  Thanks!
