### ISSUE TITLE
Subtasks for Jira Sub-Tasks

### ISSUE THREAD

**Issue by BrendanThompson** [devondragon/jira-omnifocus#32]
It would be awesome if when there was a subtask that it was also created as a subtask in OF. One would think this should be possible.

**Comment by devondragon** [comment]
OF doesn't have sub-tasks.   Or do you mean if it's in Project per Task mode? (which I don't personally use).

**Comment by orionp** [comment]
Action Groups contain Actions, and can be contained within Projects (or other Action Groups), so there's a structure that can be mapped to tasks and sub-tasks, if that's desired.

**Comment by devondragon** [comment]
Huh!  I had no idea about Action Groups!  (Shame on me!).  I will do some reading!

**Comment by devondragon** [comment]
https://support.omnigroup.com/documentation/omnifocus/mac/2.6/en/projects/

**Comment by orionp** [comment]
Hope that helps! They could certainly be easier to create on iOS, but on macOS they're *very* quick and easy!

**Comment by devondragon** [comment]
I'm going to unassign myself from this for now.  Too many other irons in the fire.
