### ISSUE TITLE
Recent problems running script

### ISSUE THREAD

**Issue by darconeous** [devondragon/jira-omnifocus#38]
All of the sudden I'm now always getting the following error:

```
/Library/Ruby/Gems/2.0.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:542:in `_send_command': CommandError (Appscript::CommandError)
		OSERROR: -1728
		MESSAGE: Can't get reference.
		OFFENDING OBJECT: app("/Applications/OmniFocus.app").default_document.flattened_contexts["Computer:Work"]
		COMMAND: app("/Applications/OmniFocus.app").default_document.flattened_contexts["Computer:Work"].tasks.get()
	from /Library/Ruby/Gems/2.0.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:642:in `method_missing'
	from ./jiraomnifocus.rb:308:in `mark_resolved_jira_tickets_as_complete_in_omnifocus'
	from ./jiraomnifocus.rb:423:in `main'
	from ./jiraomnifocus.rb:430:in `<main>'
```

This seems similar to [github-omnifocus#2](https://github.com/devondragon/github-omnifocus/issues/2).

Did OmniFocus change their script API?

**Comment by devondragon** [comment]
Did you update from GitHub recently?  An update was made four days ago that changed the way tasks are looked up in OF.  I'm wondering if that broke things for you?

**Comment by darconeous** [comment]
Well, it seems that OmniFocus wasn't liking the `:` separator for describing nested contexts. Removing that and just using the last context name fixed the problem.

Kinda weird.

**Comment by devondragon** [comment]
@darconeous - please read this issue - https://github.com/devondragon/jira-omnifocus/issues/36. and checkout the recently merged PR - https://github.com/devondragon/jira-omnifocus/pull/37. both of which may be relevant.  

I think you're basically encountering the same issue as issue 36, and when @wallacms submits his PR that should resolve it.

Let me know if I can close this issue, or if you feel there's a separate problem at play here.  Thanks!

**Comment by devondragon** [comment]
Going to close due to lack of response.
