### ISSUE TITLE
undefined local variable or method `issue'

### ISSUE THREAD

**Issue by lgrassini** [devondragon/jira-omnifocus#40]
When `mark_resolved_jira_tickets_as_complete_in_omnifocus` raises an error the error detail is referring to an undefined `issue` variable on line 378.

` raise StandardError, "Unsuccessful response code " + response.code + " for issue " + issue `

NameError: undefined local variable or method `issue' for main:Object
  bin/jiraomnifocus.rb:378:in `block (2 levels) in mark_resolved_jira_tickets_as_complete_in_omnifocus'

**Comment by lgrassini** [comment]
The solution could be replacing `issue` with `jira_id`

`raise StandardError, "Unsuccessful response code " + response.code + " for issue " + jira_id`

**Comment by devondragon** [comment]
Thank you very much!!!!  Fix is pushed!
