### ISSUE TITLE
Assignee not matching username when using Keychain (Atlassian Id)

### ISSUE THREAD

**Issue by lgrassini** [devondragon/jira-omnifocus#41]
Since Atlassian implemented https://id.atlassian.com/login now we should login to our JIRA cloud using our JIRA user email. 

This eventually may update our Keychain credential so the Keychain entry username to be our email.

This is causing `$opts[:username] = keychainitem.account` to assign our email to `$opts[:username] `. Which will not match with our assignee username (for a given JIRA issue) and causing the following block to delete our OF task:

`
              if assignee != $opts[:username].downcase
                if $DEBUG
                  puts "JOFSYNC.mark_resolved_jira_tickets_as_complete_in_omnifocus: That doesn't match your username of \"" + $opts[:username].downcase + "\" so deleting the task from OmniFocus"
                end
                omnifocus_document.delete task
              end
`

A potential solution would be evaluate the assignee also against data["fields"]["assignee"]["emailAddress"]. Example:

`
            else
              assignee = data["fields"]["assignee"]["name"].downcase
              assigneeEmail = data["fields"]["assignee"]["emailAddress"].downcase
              if $DEBUG
                puts "JOFSYNC.mark_resolved_jira_tickets_as_complete_in_omnifocus: curent assignee is: " + assignee
              end
              if assignee != $opts[:username].downcase && assigneeEmail != $opts[:username].downcase
                if $DEBUG
                  puts "JOFSYNC.mark_resolved_jira_tickets_as_complete_in_omnifocus: That doesn't match your username of \"" + $opts[:username].downcase + "\" so deleting the task from OmniFocus"
                end
                omnifocus_document.delete task
              end
`

**Comment by lgrassini** [comment]
Sure, I'm testing it now. Working fine so far. I will submit a PR after some more testing.

**Comment by devondragon** [comment]
Thank you!  I greatly appreciate it!!!

**Comment by devondragon** [comment]
@lgrassini I just wanted to check in with you and see if you'd made progress?  I don't want to bother you, but was just reviewing all open issues on my GH projects.  Thanks!  I hope all is well!

**Comment by lgrassini** [comment]
Hey @devondragon ... Sure, I'll create a PR with this this weekend. Sorry for the delay!

**Comment by devondragon** [comment]
Thanks @lgrassini !!!  Really appreciate it!

**Comment by lgrassini** [comment]
Final tests going ok. I’ll be creating the PR later today.

**Comment by devondragon** [comment]
Should be fixed, all thanks to @lgrassini !!!
