### ISSUE TITLE
Add warning on email vs username on readme

### ISSUE THREAD

**Issue by jbourdin** [devondragon/jira-omnifocus#43]
Suggestion : As the readme is the main path to configure this tool, you should definitely add a warning against #30 in the config explanation for the username (most of the time, username or email are idempotent).

**Comment by jbourdin** [comment]
In the "keychained" case I mean. I skipped the "no keychain" part and missed the warning.

**Comment by devondragon** [comment]
I've updated the README.  @jbourdin could you review and let me know if that addresses your concern or if you have any recommended changes?  Thanks!!!

**Comment by devondragon** [comment]
Closing this issue due to lack of any further feedback.
