### ISSUE TITLE
How to use with accounts authenticated via Google/GSuite?

### ISSUE THREAD

**Issue by emory** [devondragon/jira-omnifocus#44]
My Jira service uses my org's Google account to authenticate me. Is there a way to use this software in my use-case?

**Comment by devondragon** [comment]
@emory I am not sure.  I don't have any ability to test with a Google account auth....  Sorry:(. Perhaps someone else can chime in?

**Comment by darconeous** [comment]
I'm running into this myself. Jira does support [OAuth](https://developer.atlassian.com/server/jira/platform/oauth/), but this script doesn't use that.

Without the ability of the script to display a web view and allow you to authenticate to the google domain, I don't think there are a whole lot of good options unless there is a way to set up application passwords with the Jira account.

**Comment by Seklfreak** [comment]
Did you try using an API token? Works fine for me. https://confluence.atlassian.com/cloud/api-tokens-938839638.html
