### ISSUE TITLE
Basic auth with password to be deprecated on Jira Cloud - start using API tokens

### ISSUE THREAD

**Issue by mansilladev** [devondragon/jira-omnifocus#47]
See: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/

As of March 15, 2018, in accordance to the [Atlassian REST API Policy](https://developer.atlassian.com/platform/marketplace/atlassian-rest-api-policy/), Jira cloud support for passwords in HTTP basic auth requests will no longer be supported on or after September 15, 2018.

Instead of passwords, you should start using [API tokens](https://confluence.atlassian.com/cloud/api-tokens-938839638.html).

**Comment by djdesign** [comment]
@devondragon @mansilladev testing with the api_token, and Jira Cloud it appears to work currently. Tested on macOS 10.13.3.

**Comment by devondragon** [comment]
@djdesign - Do you just set the API token as the password in the jiraomnifocus configs here?  Or some other approach?  Thanks

**Comment by djdesign** [comment]
Simply, generated the token, and swapped the account_password with the new api_token.

**Comment by devondragon** [comment]
Thanks!  I have updated the documentation to reflect this!
