### ISSUE TITLE
NameError: undefined local variable or method `tag' for main:Object

### ISSUE THREAD

**Issue by poshpaws** [devondragon/jira-omnifocus#51]
Freshly installed mbp so needed to install from scratch :

M000:jira-omnifocus reidg$ bundle exec bin/jiraomnifocus.rb
Connected successfully to jira.<redacted>.corp
bundler: failed to load command: bin/jiraomnifocus.rb (bin/jiraomnifocus.rb)
NameError: undefined local variable or method `tag' for main:Object
Did you mean?  tap
  bin/jiraomnifocus.rb:278:in `block in add_jira_tickets_to_omnifocus'
  bin/jiraomnifocus.rb:262:in `each'
  bin/jiraomnifocus.rb:262:in `add_jira_tickets_to_omnifocus'
  bin/jiraomnifocus.rb:438:in `main'
  bin/jiraomnifocus.rb:449:in `<top (required)>'

latest version seems to explode :(

**Comment by devondragon** [comment]
Ugh:(. I might have broken something when trying to apply the OF3 changes.  Let me dig into it!

**Comment by devondragon** [comment]
Try updating and running it again.  Sorry!
