### ISSUE TITLE
Re-assigned tasks no longer removed

### ISSUE THREAD

**Issue by infotexture** [devondragon/jira-omnifocus#58]
> If a task has been re-assigned to someone else or unassigned it will remove it from OmniFocus.

This doesn't seem to work anymore.

I have several tickets that were previously assigned to me (and picked up in earlier `jira-omnifocus` runs) that have since been re-assigned to others, but when I re-run `jira-omnifocus` they're not removed from OmniFocus.

Has this behavior changed, or could other changes to the Jira issue be preventing `jira-omnifocus` from recognizing the tasks as the same issue that was previously added?

**Comment by devondragon** [comment]
@infotexture I'm sorry you're running into the issue!  There should have been any changes that would break that functionality, however I am not actively using JIRA myself so I haven't tested it lately.  If the title is changed in OF or Jira that could cause the issue matching to not work properly.  

Can you test with a new issue?  Assign it to yourself, run the jira-omnifocus sync, then close or unassigned it, and re-run the sync without making other changes to the ticket?

I will try to get a JIRA account setup so I can test on my end as well.

**Comment by infotexture** [comment]
@devondragon My bad. Looks like there were indeed changes on the Jira side that broke the link between the original issue and the OmniFocus task.

I tested as you suggested by creating a new issue in Jira, assigning, syncing, unassigning, and syncing again.

✅ The OmniFocus task is indeed removed.

Sorry I didn't think to test this way before filing the issue. 🤦

**Comment by devondragon** [comment]
@infotexture No problem at all!  I'm glad it turned out to not be a serious bug!
